### ISSUE TITLE
Required Properties

### ISSUE THREAD

**Issue by cnguy** [MingweiSamuel/riotapi-schema#7]
Hey!

Thank you for this project as usual. I would like to talk about adding required model properties to two cases:

1) Return Models (e.g. `summoner-v4.SummonerDTO`)
2) Models that are parameters (e.g. `tournament-v4.TournamentCodeParameters`)

https://docs.swagger.io/spec.html

![image](https://user-images.githubusercontent.com/17214097/52880359-9b890300-3116-11e9-8309-60e90221f89d.png)

The reasoning is that it allows one to generate types using [sw2dts](https://www.npmjs.com/package/sw2dts), for example.

For the first case,
Do you think it would be wise to trust that all Riot League of Legend's model DTO's to always have the properties (**required properties** as defined by Swagger).

So for example, SummonerDTO

![image](https://user-images.githubusercontent.com/17214097/52880572-2833c100-3117-11e9-8211-87ce949bf0da.png)

These fields should always exist, and so we can define them in the SwaggerSpec like so:

```
  summoner-v4.SummonerDTO:
    type: object
    title: SummonerDTO
    properties:
      profileIconId:
        type: integer
        format: int32
        x-type: int
        description: 'ID of the summoner icon associated with the summoner.'
      name:
        type: string
        x-type: string
        description: 'Summoner name.'
      puuid:
        type: string
        x-type: string
        description: 'Encrypted PUUID. Exact length of 78 characters.'
      summonerLevel:
        type: integer
        format: int64
        x-type: long
        description: 'Summoner level associated with the summoner.'
      revisionDate:
        type: integer
        format: int64
        x-type: long
        description: 'Date summoner was last modified specified as epoch milliseconds. The following events will update this timestamp: profile icon change, playing the tutorial or advanced tutorial, finishing a game, summoner name change'
      id:
        type: string
        x-type: string
        description: 'Encrypted summoner ID. Max length 63 characters.'
      accountId:
        type: string
        x-type: string
        description: 'Encrypted account ID. Max length 56 characters.'
    description: 'represents a summoner'
    required:
      - profileIconId
      - name
      - puuid
      - summonerLevel
      - revisionDate
      - id
      - accountId
```

The second case is a bit weird and really only applies to the models that are used as parameters, such as `tournament-v4.TournamentCodeParameters`.

![image](https://user-images.githubusercontent.com/17214097/52881057-6c739100-3118-11e9-8732-29e7f6f37c01.png)

In this case, I noticed that Riot doesn't really have a column to mention that something is optional, and instead places it in the description text. And so in my code, I just have something that checks for "optional" basically.

I've already coded the stuffs required to handle both cases, but it basically makes the above assumptions and is therefore hacky. Is it something safe enough to add? :O If not, I can just maintain it in a fork and keep testing.
